version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-daily-diet
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api-daily-diet
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  # cache:
  #   container_name: nest-clean-cache
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./data/redis:/data
